### ISSUE TITLE
Discord server? Forum?

### ISSUE THREAD

**Issue by markhaines** [aetaric/checkrr#111]
Hi, have just started using this and it's super useful - I've got scanning working but am having some issues connecting Sonarr + Radarr.  Where's the best place to discuss these days please, the Discord link is invalid?

**Comment by aetaric** [comment]
The discord invite looks fine to me... https://toolscord.com/invite#dkTfNKbEhJ

https://discord.gg/dkTfNKbEhJ

**Comment by aetaric** [comment]
Closing this, you can either create a blank issue and add the support label here on github or use the above discord invite to join there.
