### ISSUE TITLE
checkrr.db is a directory

### ISSUE THREAD

**Issue by ianmagnone** [aetaric/checkrr#13]
When using Docker Compose do I need to create a blank checkrr.db file? When running the container I get this in the logs repeatedly with no other progress:

Using config file: /etc/checkrr.yaml
2022/10/18 17:13:24 open checkrr.db: is a directory

**Comment by Wigglez** [comment]
Yeah you'd have to create a directory on your host path.

**Comment by ianmagnone** [comment]
It looks like checkrr is making a checkrr.db directory on first run but then stops. If I stop the container and delete that directory it recreates it.

**Comment by aetaric** [comment]
`touch /path/to/checkrr.db` should do well for you.

**Comment by ianmagnone** [comment]
Yep, that worked. :)
