### ISSUE TITLE
ts, m2ts video files reported as "unknown"

### ISSUE THREAD

**Issue by Emstar** [aetaric/checkrr#18]
ts and m2ts are less common containers, but are still legit video files. checkrr skips them as "unknown," though. 

I know you are using middleware like `ffprobe` so this may just be how it is.

**Comment by aetaric** [comment]
Looks like it's actually going to be the pre-ffprobe checks using `h2non/filetype` that fail here. I'll have to PR MPEG-TS's Magic Number data into that library here: https://github.com/h2non/filetype/blob/v1.1.3/matchers/video.go if we want to validate that. ffprobe should have no direct issue with it.

**Comment by Emstar** [comment]
Makes sense. I'll test it if it shows up in a release! I don't have many such files and with the recent ignore list changes, checkrr is highly functional for me. :)

**Comment by aetaric** [comment]
Sounds good. I filed h2non/filetype#120 So they can get that added in a somewhat sane way as the magic number for MPEG-TS is 0x47 every 188 bytes... which seems messy...

On the testing side, I am VERY familiar with the MPEG-TS standard, so I'll be able to rapidly transcode a few files over to both a single .ts file and a manifest driven .ts file per GoP (Group of Pictures) with a simple enough FFMPEG command. Always willing to have the additional testing though as it will only serve to provide better data on if checkrr is working as expected.

**Comment by Emstar** [comment]
Sweet, thanks!

**Comment by TheRedSpy15** [comment]
I'm using 3.2.1 and my m2ts files are still being reported as unknown

**Comment by aetaric** [comment]
> I'm using 3.2.1 and my m2ts files are still being reported as unknown

what's the output of `ffprobe filename.m2ts`? and what does `file filename.m2ts` report it as?

**Comment by TheRedSpy15** [comment]
> > I'm using 3.2.1 and my m2ts files are still being reported as unknown
> 
> what's the output of `ffprobe filename.m2ts`? and what does `file filename.m2ts` report it as?

ffprobe:
```
ffprobe version 6.0-full_build-www.gyan.dev Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 
--enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[mpegts @ 00000215f785e380] start time for stream 3 is not set in estimate_timings_from_pts
[mpegts @ 00000215f785e380] start time for stream 4 is not set in estimate_timings_from_pts
[mpegts @ 00000215f785e380] start time for stream 5 is not set in estimate_timings_from_pts
[mpegts @ 00000215f785e380] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle (pgssub) ([144][0][0][0] / 0x0090)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 00000215f785e380] Could not find codec parameters for stream 4 (Subtitle: hdmv_pgs_subtitle (pgssub) ([144][0][0][0] / 0x0090)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[mpegts @ 00000215f785e380] Could not find codec parameters for stream 5 (Subtitle: hdmv_pgs_subtitle (pgssub) ([144][0][0][0] / 0x0090)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mpegts, from 'G:\Movies\Azumi (2003)\00008.m2ts':
  Duration: 02:15:02.98, start: 600.000000, bitrate: 23396 kb/s
  Program 1
  Stream #0:0[0x1011]: Video: h264 (High) (HDMV / 0x564D4448), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn
  Stream #0:1[0x1100]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 448 kb/s
  Stream #0:2[0x1101]: Audio: pcm_bluray (HDMV / 0x564D4448), 48000 Hz, stereo, s16, 1536 kb/s
  Stream #0:3[0x1200]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090)
  Stream #0:4[0x1201]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090)
  Stream #0:5[0x1202]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090)
```

And I don't have the `file` command on Windows 10

**Comment by aetaric** [comment]
Yeah, m2ts isn't _really_ going to ever work that well. It's not meant to be a file format. It's a container format specialized for transmission. ffmpeg can transmux the container over to something like mp4 or mkv pretty easily. The hacked in support does still work, it's just that trying to determine the type via magic number (the step that is likely failing) isn't cut and dry like mp4, mkv, avi, etc.

`ffmpeg -i input.mt2s -scodec copy -acodec copy -vcodec copy -f matroska output.mkv` should readily convert the container to mkv as an example, though you might want mp4 for compatibility with devices that can't read mkv files if you are concerned about PMS transcoding. Fairly easy to google around for the command syntax there, and safe because it only ever reads the source file.
