### ISSUE TITLE
FR: option to disable notifications

### ISSUE THREAD

**Issue by mgaulton** [aetaric/checkrr#20]
When not wanting to use discord, it errors on a blank config, which I thought would be enough to disable. 
`INFO[0000] Using config file: ./checkrr.yaml
INFO[0000] Sonarr integration not enabled. Files will not be fixed. (if you expected a no-op, this is fine)  Sonarr Connected=false Startup=true
INFO[0000] Radarr integration not enabled. Files will not be fixed. (if you expected a no-op, this is fine)  Radarr Connected=false Startup=true
INFO[0000] Lidarr integration not enabled. Files will not be fixed. (if you expected a no-op, this is fine)  Lidarr Connected=false Startup=true
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x758fe9]

goroutine 1 [running]:
github.com/aetaric/checkrr/check.(*Checkrr).connectNotifications(0xc000004280?)
        /opt/radarrplugins/checkrr/check/checkrr.go:205 +0x89
github.com/aetaric/checkrr/check.(*Checkrr).Run(0xc000004280)
        /opt/radarrplugins/checkrr/check/checkrr.go:60 +0x277
main.main()
        /opt/radarrplugins/checkrr/main.go:86 +0x574
`

**Comment by aetaric** [comment]
@mgaulton 2.0.1 is rolling out to fix this. Thanks for the heads up. Was missing a nil check.
