### ISSUE TITLE
Install docs need some attention in the readme

### ISSUE THREAD

**Issue by aetaric** [aetaric/checkrr#29]
As was pointed out on a reddit thread, the install docs make a lot of assumptions about the knowledge of the user. Provide actual installation documentation in the readme.

**Comment by hardybm** [comment]
I wrote up a little bit in my comment. I can format it further if you like. I'm a cli-comfortable but docker/git noob so probably the appropriate reading level.

**Comment by hardybm** [comment]
Can’t be helpful without throwing some snark in, hey
