### ISSUE TITLE
Healthchecks integration

### ISSUE THREAD

**Issue by karan** [aetaric/checkrr#3]
https://healthchecks.io/docs/

I am currently doing this manually using `curl` but it would be a nice-to-have to be natively integrated.

**Comment by aetaric** [comment]
So, reading up on this... It's a periodic script/program monitoring system to ensure the script is running on the scheduled interval? Doesn't look like it would be too hard to implement, though I'm curious to what level of utilization it would get....

**Comment by mjefferys** [comment]
I'd defo like this one, I have healthchecks.io hooked up to my discord to ping me if my nightly backup jobs fail or overrun. You can tell healthchecks how long you expect a process to run for and if it runs for longer than that it's usually a sign of an issue which I think might be quite useful for checkrr. Healthchecks also gives you a nice historical view of every run.

Basically your app pings the healthchecks.io server when the process starts, and again upon completion. There are no extra processes for monitoring on the server, you just ping a user-configured endpoint.

I know you've already got discord but this would be a nice addition.

**Comment by aetaric** [comment]
> You can tell healthchecks how long you expect a process to run for

See therein lies an issue. My first run of Checkrr on my own library back before 1.0.0 was published took 30 hours to complete. Runs today take anywhere from 20 seconds to 2-5 minutes depending on how much read utilization my ZFS pool already has.

I don't mind implementing something like this, but there are too many variables to guess how long a task of this size will take. I assume this is a *can* versus *have to* situation, but this will not be fully featured in your healthchecks.io environment. If start and completed is fine, then I can look at adding it. Time to Complete is not possible.

**Comment by aetaric** [comment]
After reading over the docs, it looks like there's a lot of features to this that would increase code complexity beyond a few lines here or there... namely having to call a failure where checkrr would otherwise call Fatal() or Panic(). This can easily be done in bash...

```
#!/bin/bash

UUID=uuid-here
BASE_URL=https://hc-ping.com

curl -XGET $BASE_URL/$UUID/start

checkrr check

curl -XGET $BASE_URL/$UUID/$?
```

That will literally take the exit code and pass it over to healthcheck.io where they will process `0` as success and any other value as failure, per standard POSIX compliant exit code logic. Which is what Checkrr does.

**Comment by aetaric** [comment]
With 2.x being live, this makes sense to implement.
