### ISSUE TITLE
ignoreext fails to properly ignore the file extention

### ISSUE THREAD

**Issue by joggs** [aetaric/checkrr#31]
Using the example config file makes checkrr report every .bif file as a bad file (whcich could be an improvement to add .bif to ignoreexts in the yaml, as I think the greater part of users have .bif files autogenerated for video files in plex, emby etc).
But the issue here is, that if I add .bif to the ignoreexts section in the config, they are still found by checkrr and treated as a bad file(ignore faulty indent. the yaml is valid).

my config:
ignoreexts:
     - .txt
     - .nfo
     - .nzb
     - .url
     - .bif
radarr: ....

I've deleted the database and re created the docker between tests.

**Comment by wieluk** [comment]
same for me for .xml files

**Comment by TuRDMaN** [comment]
I am on the latest version and still getting "unknown file detected" for all sorts of files that are defined in ignoreexts:

**Comment by aetaric** [comment]
> I am on the latest version and still getting "unknown file detected" for all sorts of files that are defined in ignoreexts
That's because 3.1.0 isn't released. This will be patched in that version.

**Comment by TuRDMaN** [comment]
Ah, okay. Thanks for all of your work.

Looking forward to it!
