### ISSUE TITLE
[Feature Request] Support postgres

### ISSUE THREAD

**Issue by Xstar97** [aetaric/checkrr#32]
Hi i like to request postgres support, having the database as a separate instance and being postgres is much more manageable and faster than a sqlite db.

**Comment by aetaric** [comment]
It's actually not sqlite! It's [bbolt](https://github.com/etcd-io/bbolt). A lightning fast key/value flat file database written in go. I don't need the features from a sql database (relations), so postgres would be incredibly bulky, would require a lot of code to change, and would require users to setup an entirely new database engine just to run checkrr.

**Comment by Xstar97** [comment]
Ahh ok, thanks for clarifying.
