### ISSUE TITLE
[Feature] show next scan time / schedule info

### ISSUE THREAD

**Issue by rickatnight11** [aetaric/checkrr#34]
With a new install using the default `cron: "@daily"` setting, it's not clear when the first scan will actually occur.  It would be useful to show the user in the WebUI what the schedule is set to and when the next scan will run.

**Comment by aetaric** [comment]
<img width="459" alt="Screenshot 2023-01-13 at 2 26 33 AM" src="https://user-images.githubusercontent.com/565454/212285304-6be70b42-670d-42dd-a10b-2d74a07b2529.png">
Hopefully this works well enough. I went with a fuzzy time as it avoids confusion. It's moment.js, so it'll scale down sanely as it gets closer to run time.
