### ISSUE TITLE
[Feature] Add ignorepath support

### ISSUE THREAD

**Issue by randomparity** [aetaric/checkrr#35]
Radarr/Sonarr/Lidarr allow deleted files to be moved to a user specified filepath before copying  any files from a newer download.  If that filepath happens to be in the existing "checkpath" configuration, checkrr will scan them unnecessarily.  Adding a configuration option to ignore certain filepaths would eliminate the unnecessary file checks.

**Comment by hardybm** [comment]
This would also be useful for synology users. Synology indexing and thumbnail generation creates an @eaDir folder which checkrr then identifies as having something wrong with it.
