### ISSUE TITLE
[Feature] Add support for Gotify

### ISSUE THREAD

**Issue by LargeTalons** [aetaric/checkrr#36]
https://gotify.net/

Works just like Pushover does but its self hosted.

**Comment by aetaric** [comment]
@LargeTalons Do you run checkrr in a container, or with the binary? If you run with the binary, I can produce a test binary to confirm this works before committing it to 3.1.0.

**Comment by LargeTalons** [comment]
I run it in a docker on unraid

**Comment by aetaric** [comment]
Fair enough. Guess I need to setup a gotify instance then. 🙃
