### ISSUE TITLE
Request: docker image for 3.1.1

### ISSUE THREAD

**Issue by douginoz** [aetaric/checkrr#46]
It doesn't appear that the docker image aetaric/checkrr:latest has been updated to 3.1.1 yet.  aetaric/checkrr:3.1.0 doesn't work so I'm assuming aetaric/checkrr:3.1.1 doesn't either.

**Comment by douginoz** [comment]
whoops!  aetaric/checkrr:3.1.1 works great.  Thanks!

**Comment by aetaric** [comment]
Latest on both github and docker matches the hashes for 3.1.1 as well, so, idk what's up there.
