### ISSUE TITLE
[Request] Hovering over 'bad' filename displays complete path/file

### ISSUE THREAD

**Issue by douginoz** [aetaric/checkrr#48]
Currently the only way to identify the files identified as bad is to export them to a csv.  Widening the window doesn't change the width of the columns.  Hovering the mouse over the partially-displayed name could bring up the complete file and path.

**Comment by aetaric** [comment]
Seems easy enough, pretty sure it just needs a tooltip added to that column.

**Comment by aetaric** [comment]
Closing in favor of #52
