### ISSUE TITLE
DNS in docker image not working with checkrr

### ISSUE THREAD

**Issue by quorn23** [aetaric/checkrr#51]
`{"Radarr \"radarr\" Connected":false,"Startup":true,"level":"info","msg":"api.Get(v3/system/status): httpClient.Do(req): Get \"http://\u003cnil\u003e:7878/api/v3/system/status\": dial tcp: lookup \u003cnil\u003e: no such host","time":"2023-01-24T21:08:09Z"}`

No matter if i try
`    address: radarr`
`    address: "radarr"`
`    address: http://radarr`
`    address: "http://radarr"`

Checkrr throws the no such host error. If i use the internal docker ip it works fine.
exec into the container i can ping the container radarr fine. If i recall correctly, there is some go bind module (might be the wrong terminology) that needs to be included, so the app can use the dns properly. Our mate David Newhall might remember what it was, i believe we had the issue with Notifiarr as well at one point.

Edit: Output with the internal container ip of radarr
`{"Radarr \"radarr\" Connected":true,"Startup":true,"level":"info","msg":"Radarr Connected.","time":"2023-01-24T21:15:31Z"}`
In config:
`    address: "10.1.0.20"`

**Comment by aetaric** [comment]
Captain gave me the build flag. I'll get this sorted in 3.1.2.
