### ISSUE TITLE
checkrr not doing anything

### ISSUE THREAD

**Issue by Jorgisimo** [aetaric/checkrr#54]
hey guys i am sure i messed up something, but for the life of me i cant figure it out. checkrr runs, but never updates. I have a docker box that also runs my sonarr and radarr

i created the docker container as follows

`docker create --name checkrr --restart unless-stopped -p 8585:8585 -e PUID=1026 -e PGID=100 -e TZ='America/New_York' -v /etc/localtime:/etc/localtime:ro -v /DOCKER/CHECKRR/checkrr.yaml:/etc/checkrr.yaml -v /DOCKER/CHECKRR/checkrr.db:/checkrr.db -v /mnt/MEDIA/TV:/tv -v /mnt/MEDIA/ANIME:/anime -v /mnt/MEDIA/MOVIES/:/movies aetaric/checkrr:latest`

i downloaded the example file and just created what i needed REMOVED API keys

`checkrr:
  checkpath:
      - "/movies"
    - "/tv"
    - "/anime"
  database: ./checkrr.db
  debug: true
  csvfile: ./badfiles.csv
  logfile: ./checkrr.log
  logjson: false
  cron: "@daily"
  ignorehidden: true
  ignorepaths:
  ignoreexts:
    - .txt
    - .nfo
    - .nzb
    - .url
arr:
  radarr:
    process: true
    service: radarr # should be one of: sonarr radarr lidarr
    address: docker01
    apikey: "REMOVED"
    baseurl: /
    port: 7878
    mappings: # maps directories between docker and arr services
      "/movies": "movies" # what radarr sees: what checkrr sees
  sonarr:
    process: true
    service: sonarr
    address: docker01
    apikey: "REMOVED"
    baseurl: /
    port: 8989
    mappings:
      "/tv": "/tv"
  anime:
    process: true
    service: sonarr
    address: docker01
    apikey: "REMOVED"
    baseurl: /
    port: 8989
    mappings:
      "/anime": "/anime"
notifications:
  pushover:
    apitoken: "REMOVED"
    recipient: ""
    notificationtypes:
      - reacquire
      - unknowndetected
      - startrun
      - endrun
stats: # These will slow down the runtime substantually, but... DATA
webserver:
  port: 8585
  baseurl: "/"
  trustedproxies:
    - 127.0.0.1
`

Checkrr runs i see the gui, but nothing happens

![image](https://user-images.githubusercontent.com/50676534/224128738-c07d01ab-1603-457d-a966-e0dad5434928.png)

**Comment by aetaric** [comment]
do you see it running in `docker logs -f checkrr` ?

**Comment by Jorgisimo** [comment]
Logs were blank. Only logs I saw was when I access the web page. I am trying some stuff tonight to see if I can figure out what’s wrong. But figured I would take a stab here if I missed anything obvious.

Jorge L Duran

________________________________

**Comment by Jorgisimo** [comment]
so made some progress creating the csvfile and logfile and giving them their own volume got it to scan. its hashing, but I don't see it talking to radarr or sonarr I'll give it the night to run to see if it updates the UI.

changing 
`checkrr:
  checkpath:
    - "/movies"
    - "/tv"
    - "/anime"
  database: ./checkrr.db
  debug: true
  csvfile: ./badfiles.csv
  logfile: ./checkrr.log
  logjson: false
  cron: "@daily"
  ignorehidden: true
  ignorepaths:
  ignoreexts:
`

![image](https://user-images.githubusercontent.com/50676534/224197899-8efea61b-4ba5-4bfe-904f-8f160b33f2f1.png)

**Comment by aetaric** [comment]
You'd have to double check your mappings. The format for mappings is `"path arr service sees": "path checkrr sees"`. If the paths on the arr side don't match what the arr service sees on disk, it will not match to the service. 

Checkrr walks through file roots in the arr service to find matching paths swapping out what it sees for the what the arr service is expected to see. So if they don't match in the config, it'll never identify the right service.

**Comment by Jorgisimo** [comment]
Checked mapping last night and they are right. I am going to go thru the logs again and see if I see any errors. For sure sonarr and radarr aren’t working and my pushover isn’t sending notifications so I guess I have something wrong after the scan section keeping the bottom from processing right.

**Comment by Jorgisimo** [comment]
so spent a few hours and it seems the issue is that it was not connecting to sonarr and radarr. i tried FQDN, shortcut names with and without quotes. nothing was working. changed the address to the IP and its finally working. not sure why the addresses didnt working since overserr and other apps use the same address and port combinations, but progress!

**Comment by aetaric** [comment]
> my pushover isn’t sending notifications

Did you set the recipient? can be a group chat token or a user token, but it must be a valid notification token. See also: https://github.com/gregdel/pushover#send-a-simple-message if you happen to be able to read golang...

**Comment by Jorgisimo** [comment]
Work has kept me from doing too much testing in the last few days I created an app in pushover deleted the tokens I had in there and I am trying again tonight. If it doesn’t work I’ll try my sonarr ones to see if it’s something wrong with the new app token.

**Comment by aetaric** [comment]
As mentioned in #56, remove the logfile directive if you want the logs to goto standard out instead of a file.

**Comment by Jorgisimo** [comment]
yup alert started working! thanks for everything
