### ISSUE TITLE
[Feature] Add date column to the bad files table

### ISSUE THREAD

**Issue by misleadingrhino** [aetaric/checkrr#59]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
Column in the bad files table for the date it was added to the list so we can see new files being added and ignore corrected ones.

**Describe alternatives you've considered**
No alternative

**Additional context**
None

**Comment by aetaric** [comment]
<img width="1156" alt="Screenshot 2024-10-08 at 00 03 13" src="https://github.com/user-attachments/assets/da6f116e-272d-4344-96a3-c847572493b6">
Hopefully that's what you intended here. If so, it will be in 3.4.0 for all future files after that upgrade.
