### ISSUE TITLE
--checkPath command line option is not respected

### ISSUE THREAD

**Issue by mjefferys** [aetaric/checkrr#6]
Running the following

`./checkrr check --database checkrr.db --checkPath /media/Crap/`

Causes no output, but putting 

`checkPath: /media/Crap/`

In config, it does successfully check. Would be nice if the command line options worked for testing. Although long term I probably will switch to having everything in config anyway.

**Comment by aetaric** [comment]
Hey, I've got a fix for this in [39c4670](https://github.com/aetaric/checkrr/commit/39c46704f55976701284cec3a73abf132810695e). Will roll out with 1.1.2.
