### ISSUE TITLE
[BUG] 3.1.3 release does not include frontend changes

### ISSUE THREAD

**Issue by hugo-vrijswijk** [aetaric/checkrr#66]
**Describe the bug**
I think something went wrong with the last 3.1.3 release, because the frontend seems to be an older version. Maybe something went wrong with publishing and it took an older built version that was still on disk?

**To Reproduce**
1. Open latest checkrr release and open the frontend (and console.log errors)
2. Build latest release locally and observe the differences

**Expected behavior**

Latest release should include latest frontend changes too

**Screenshots**

3.1.3 Release: ![image](https://github.com/aetaric/checkrr/assets/10114577/d098dfda-7755-400f-9b1a-6ad3f1e81fc0)
Built locally: ![image](https://github.com/aetaric/checkrr/assets/10114577/8b988711-c7a3-459d-b055-02cdabb928ad)

**Desktop (please complete the following information):**
 - OS: Linux and macOS
 - Browser: Chrome and firefox latest 
 - checkrr Version: 3.1.3

**Comment by aetaric** [comment]
It looks like goreleaser didn't build the new frontend because I was missing vite. Probably just gonna version bump it to resolve.

**Comment by hugo-vrijswijk** [comment]
Any update on this?

**Comment by aetaric** [comment]
Sorry, been busy with a new job. Release pushed as 3.1.4 with a few other small fixes and dep bumps.

**Comment by hugo-vrijswijk** [comment]
No worries, thanks!
