### ISSUE TITLE
[BUG] nil pointer reference with Splunk

### ISSUE THREAD

**Issue by TSavo** [aetaric/checkrr#76]
**Describe the bug**
Checkrr version 3.2.0
Commit: e6e3d6d6c62341201ef31574e1256c09de135862
Built On: 2023-10-05T02:14:14Z
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xbb54f4]

goroutine 130 [running]:
github.com/aetaric/checkrr/features.(*Stats).Write.func1({0xc000038aa0, 0x654966b5, {0xfcc6e5, 0x6}})
        /Users/aetaric/src/checkrr/features/stats.go:208 +0x314
created by github.com/aetaric/checkrr/features.(*Stats).Write in goroutine 1
        /Users/aetaric/src/checkrr/features/stats.go:195 +0x51e

**To Reproduce**
Start Checkrr with the minimal config

**Expected behavior**
Checkrr to work

**Desktop (please complete the following information):**
 - OS: Windows x86/64
 - checkrr Version: 3.2.0

**Additional context**
I know this is fixed in main, any chance we can get a release for it?

**Comment by aetaric** [comment]
It's in 3.2.1 now. Thanks for reminding me!
