### ISSUE TITLE
Filter by Audio/Video Codec? [Feature]

### ISSUE THREAD

**Issue by Tharic99** [aetaric/checkrr#84]
**Is your feature request related to a problem? Please describe.**
Radarr displays the Audio/Video codec as well as the quality. However, it does not allow you to filter by the Audio/Video codec. For example, if a movie is an AVC or an x265 video codec or DTS-HD MA - 5.1 or AAC - 2.0 audio codec.

**Describe the solution you'd like**
Solution would be to be able to input the audio/video codec you do NOT want. Then Checkrr would find any files with that audio/video codec match, determine them to be "unwanted" and send a request to Radarr/Sonarr to force a new download.

Essentially this would add custom healthchecks in the config to enable the ffprobe to find the codec not wanted. Perhaps a comma separated list, one for audio and one for video? Maybe in quotes just in case?

```
RemoveVideo: "AVI", "AVC", "h265"
RemoveAudio: "DTS-HD MA - 5.1","DTS - 5.1"
```

You would probably need to maintain a list of audio/video codex so someone didn't put "h.265" or "h265" or "x265" or "265" all for the same thing.

**Describe alternatives you've considered**
- Manually going through Radarr/Sonarr to force new download on media.
- Running a bash script to identify the media by file name and removing it.
- Converting the media format using something like Tdarr.

**Comment by aetaric** [comment]
This is a pretty solid idea. I'll look into getting it into the next major or minor release.

**Comment by aetaric** [comment]
```
INFO[0041] test/Movies/Big Buck Bunny (2008)/Big Buck Bunny (Sunflower Movie Version) (2008).mp4  FFProbe=true Format="QuickTime / MOV" Type=Video
INFO[0041] mov,mp4,m4a,3gp,3g2,mj2                      
INFO[0041] h264                                         
INFO[0041] Detected h264. Removing.                      FFProbe=true Format="QuickTime / MOV" Type=Video
INFO[0041] Couldn't find a target for file "test/Movies/Big Buck Bunny (2008)/Big Buck Bunny (Sunflower Movie Version) (2008).mp4". File is unknown.  Unknown File=true
```

Confirmed working with [8aa5f15](https://github.com/aetaric/checkrr/commit/8aa5f1566b369056b247fb84362cf455e2d87232)
