### ISSUE TITLE
[Feature] Whisparr Support

### ISSUE THREAD

**Issue by thorman123** [aetaric/checkrr#85]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Whisparr support

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by aetaric** [comment]
Blocked by golift/starr#127

**Comment by aetaric** [comment]
@thorman123 Do you run checkrr as a standalone executable or via docker?

**Comment by aetaric** [comment]
[checkrr_whisparr_test.zip](https://github.com/aetaric/checkrr/files/13664722/checkrr_whisparr_test.zip)
I chatted with the starr devs and it seems their unpackarr tool ties into whisparr via the sonarr API. The attached test build attempts to do the same thing, If you can test that and confirm it works as expected with whisparr, I'll go ahead and get this added for the next major/minor release.

**Comment by aetaric** [comment]
Interesting... This new build has extra debug logging in the sonarr API logic. If there's an error being thrown, as long as you have debug set to true in the config or run it with --debug it should print info about the series and episode id and any error calling the delete file endpoint.
[checkrr_whisparr_debug.zip](https://github.com/aetaric/checkrr/files/13680250/checkrr_whisparr_debug.zip)

**Comment by aetaric** [comment]
Sorry, I forgot to switch branches on the machine I built that on. I rebuilt it with the whisper changes AND the debug logging.
[checkrr_whisparr_debug.zip](https://github.com/aetaric/checkrr/files/13680738/checkrr_whisparr_debug.zip)

**Comment by aetaric** [comment]
Yeah, Whisparr doesn't have it's own API, they are using sonarr's API. (if you are doing series and episodes there's not really a reason to make a custom API when sonarr's will work)

The proposed Whisparr support would just leverage the sonarr API (though, you could take 3.2.2 and connect whisparr as `service: sonarr` and it would work fine). With the `--debug` flag, or setting `debug: true` in the config under checkrr, any file replacements that match file paths with whisparr's (or sonarr's) configured root directories will log additional information like the series id, the file id, and any error calling delete on the file id.

**Comment by aetaric** [comment]
Files are checked by looking at the magic number and checking if ffprobe can parse the container. A hash mismatch might not be a bad file, just that the file changed from the expected hash.

In windows, you should be able to create a junk data file with `fsutil file createnew test.mp4 32234`. That's almost certain to fail the magic number check.

**Comment by aetaric** [comment]
Is `K:\Data\Media\Test` a root folder for Whisparr? if not, it will not match to that service. When I setup test media, I move a known good file out of the way and replace it with a junk file like that in a root folder that matches the service I am testing.

Checkrr doesn't know what service to contact unless it can find a matching root folder in one of the configured services.

**Comment by aetaric** [comment]
Ah, as long as the filename is a filename of a tracked file for whisparr in it's root directory, it should find it in Whisparr's API to remove it. That's why I make a copy of a known good file and then replace it with a junk file of the same name when testing. checkrr has to find the file in the API by filename, without it being found it will still fail to match to a service.

**Comment by aetaric** [comment]
To explain what's happening with `\\`, Windows is the only OS to use `\` as a path separator. Every other OS uses `/`. Checkrr natively supports OS specific path speparators, but it has to log with doubled `\` to avoid using it for what every other system uses it for, an escape character. 

On the off chance I missed something implementing whisparr as a unique type, does it contact the service if you use `service: sonarr`?

**Comment by aetaric** [comment]
To be clear, checkrr doesn't actually delete the files itself. it expects the configured arr services to delete the files and calls their delete api if it can match the file to a known file in them. I'm not aware of any issues in any current checkrr version not being able to trigger that call. 

I'll close this issue as whisparr should work fine with as a sonarr configured service.
