### ISSUE TITLE
[Feature] Support SSL for connected services

### ISSUE THREAD

**Issue by Hampo** [aetaric/checkrr#88]
**Is your feature request related to a problem? Please describe.**
The URL for connected services assumes `http`, however I have Sonarr and Radarr on `https` with an SSL cert.

**Describe the solution you'd like**
Change [Lidarr](https://github.com/aetaric/checkrr/blob/main/connections/lidarr.go#L90), [Radarr](https://github.com/aetaric/checkrr/blob/main/connections/radarr.go#L69) and [Sonarr](https://github.com/aetaric/checkrr/blob/main/connections/sonarr.go#L72)'s config to support a yaml entry like `address: "https://radarr.example.com"`.

**Comment by aetaric** [comment]
I will not change the lines to support using a URL as an "address", but I did change it to swap the http to https based on an SSL option.

Changing it to a URL would be a breaking change, while defaulting to current behavior and adding an SSL option is much easier on users that blindly update without checking the release notes.

Hopefully this is a middle ground that will still work for your needs, but will be less intrusive of a change.
