### ISSUE TITLE
[BUG] checkrr is stuck in running state after SIGSEGV, OoMKiller invocation, or other calls to kill() for checkrr's pid

### ISSUE THREAD

**Issue by steve1977** [aetaric/checkrr#91]
I have installed Checkrr in Docker container on Unraid (via CA). To start with, I have only set up connection with Radarr.

After starting the docker, I hit "run now" in the GUI. It seems to work and it identifies a few bad files and seems to have scanned my whole library. So far, so good!

However, it doesn't seem to stop and doesn't allow me to restart. GUI always says "running" and "run now" is greyed out. Even after restarting the docker, this doesn't change. No info in docker log and log file.

Any thoughts what I can try to troubleshoot?

**Comment by aetaric** [comment]
Checkrr periodically writes to a table in the the db file with the "current stats" and that's one of the states that is tracked with that write. There's a stop function that sets running to false and the button is only enabled when running is set to false. 

If checkrr never writes `running: false` to that table, the button will not re-enable. (this could occur if checkrr is killed by OOMKiller or SIGKILL before it can write that state)

You can try clearing the state by hitting checkrr's API for run: `curl -X POST http://address.to.checkrr.web:port/api/run`.

If you can't for some reason send a post request to that endpoint, if you delete the DB file, recreate it with the touch command again, it should free up checkrr to run again, though it will lose it's hashes of the current files.

**Comment by aetaric** [comment]
This issue has been open a few months with no reply. I'll close it now, if you are still having issues, just reply and I'll reopen it.

**Comment by aetaric** [comment]
reopening to patch this in bug in 3.4.0.

**Comment by aetaric** [comment]
Patch will be in 3.4.0.

```
[1]  + 48670 killed     ./checkrr -c test-noarr.yaml                                                                                                  
➜  checkrr git:(main) ✗ ./checkrr -c test-noarr.yaml

            _|                               _|
   _|_|_|   _|_|_|       _|_|       _|_|_|   _|  _|     _|  _|_|   _|  _|_|
 _|         _|    _|   _|_|_|_|   _|         _|_|       _|_|       _|_|
 _|         _|    _|   _|         _|         _|  _|     _|         _|
   _|_|_|   _|    _|     _|_|_|     _|_|_|   _|    _|   _|         _|
Checkrr version development
 Commit: 
 Built On: 
 Built By: 
INFO[0000] Using config file: test-noarr.yaml           
WARN[0000] Cleaing up previous crash or improper termination of checkrr.  startup=true
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
```
