### ISSUE TITLE
[Feature] SSL on Web Server

### ISSUE THREAD

**Issue by smarthome-enthusiast** [aetaric/checkrr#94]
**Is your feature request related to a problem? Please describe.**
I'm trying to have Checkrr displayed on HomeAssistant through an iFrame but I'm unable to load HTTP inside a HTTPS web server.

**Describe the solution you'd like**
Would it be possible to support SSL? Maybe through the config under the webserver options, we could specify the certificate and key and enable SSL on the same port. i.e port 8585 is either served as HTTP or HTTPS.

**Describe alternatives you've considered**
Disabling HTTPS on HomeAssistant but that would make it very insecure during external access.

**Comment by aetaric** [comment]
hey @smarthome-enthusiast This was just added in [d5532b1](https://github.com/aetaric/checkrr/commit/d5532b10e498716e42773ea603e9f45f7e6bc134). If possible, could you test a local build of checkrr from main? Just want to make sure it's working for your usecase prior to 3.4.0's release.

**Comment by aetaric** [comment]
confirmed working with a self-signed cert. Closing as completed.
<img width="849" alt="Screenshot 2024-10-08 at 11 02 03" src="https://github.com/user-attachments/assets/3cdcafdd-4f7c-497a-989d-b37c9751a1d0">
<img width="1292" alt="Screenshot 2024-10-08 at 11 03 09" src="https://github.com/user-attachments/assets/7c4b9e45-3368-442e-8b81-d1acbf39c874">
