### ISSUE TITLE
Not doing anything in Radarr or Sonarr[BUG]

### ISSUE THREAD

**Issue by trsmith78** [aetaric/checkrr#99]
Hey,
I like the program, it has gone through all of my libraries and found about 150 problems.
I have the list, so I can do delete them and had then sonarr and radarr will go find new ones (if I have those files monitored), but I thought this program did that automatically.  If so, I can't figure out how to get it to work.  The webui is working, and I see the list there.  I don't get any errors.  And right now I'm just exporting it to a .csv and manually deleting.  Many thnaks!

 Here is my config.

checkrr:
  checkpath: 
    - "d:/media/movies"
    - "d:/media/Movies (Spanish)"
    - "d:/media/tv shows"
    - "d:/media/TV Shows (Spanish)"
    - "e:/media/movies"
    - "e:/media/Movies (Spanish)"
    - "e:/media/tv shows"
    - "e:/media/TV Shows (Spanish)"
    - "g:/my drive/media/movies"
    - "G:/My Drive/Media/Movies (Spanish)"
    - "g:/my drive/media/tv shows"
    - "g:/my drive/media/TV Shows (Spanish)"

  database: ./checkrr.db
  debug: true
  logjson: false
  ignorehidden: true
  csvfile: "./badfiles.csv"
  logfile: "./checkrr.log"
  ignoreexts:
    - .txt
    - .nfo
    - .nzb
    - .url 
arr:
  radarr:
    process: true
    service: radarr # should be one of: sonarr radarr lidarr
    address: 127.0.0.1
    apikey: "redacted"
    baseurl: /
    port: 7878
    ssl: false
    #mappings: # maps directories between docker and arr services
      #"/mnt/user/Movies/": "/Movies/" # what radarr sees: what checkrr sees
  sonarr:
    process: true
    service: sonarr
    address: 127.0.0.1
    apikey: "redacted"
    baseurl: /
    port: 8989
    ssl: false
   # mappings:
    #  "/mnt/user/tv/": "/tv/"
webserver:
  port: 8585
  baseurl: "/"
  trustedproxies:
    - 127.0.0.1

**Comment by aetaric** [comment]
hey, a couple of questions:

1. what does the log file say about sonarr and radarr?
2. what version of sonarr and radarr are you running?

**Comment by trsmith78** [comment]
> hey, a couple of questions:
> 
> 1. what does the log file say about sonarr and radarr?
> 2. what version of sonarr and radarr are you running?

1.  Let me investigate.  the only log I see in the checkrr.log file are these 2 entries at the top.  Everything else is just the results from ffprobe.  is there another log file, or something I have to enable to get more logging detail?
time="2024-07-04T00:19:48-05:00" level=info msg="Sonarr Connected." Sonarr "sonarr" Connected=true Startup=true
time="2024-07-04T00:19:48-05:00" level=info msg="Radarr Connected." Radarr "radarr" Connected=true Startup=true
2.  Versions:
sonarr 4.0.6.1805
radarr 4.0.6.1805

Thank you for your quick response and your time!
Troy

**Comment by aetaric** [comment]
sonarr 4.x and radarr 5.x aren't currently supported: https://github.com/aetaric/checkrr/issues/81

**Comment by trsmith78** [comment]
> sonarr 4.x and radarr 5.x aren't currently supported: https://github.com/aetaric/checkrr/issues/81

Ok.  Sorry I missed that.
Does checkrr still run on to identify the corrupt files?

**Comment by aetaric** [comment]
Yeah, it works without sonarr and radarr integrated, it just can't tell them fetch replacements if the version is too new.

**Comment by aetaric** [comment]
closing as duplicate
